trigger:
- main

variables:
  - group: 'azure-variables'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy Azure Infrastructure'
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName) --location $(location)

    - task: AzureCLI@2
      displayName: 'Deploy Log Analytics Workspace using Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file logAnalytics.bicep \
            --parameters logAnalytics.parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'Deploy ACR using Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file acr.bicep \
            --parameters acr.parameters.bicepparam
     
    - task: AzureCLI@2
      displayName: 'Deploy AKS using Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file aks.bicep \
            --parameters aks.parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'Deploy Azure SQL Database using Bicep'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file sql.bicep \
            --parameters sql.parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'Deploy Storage account to store Audit logs for Sql Server'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file storageAccount.bicep
            --parameters parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'Deploy Key vault to store storage account key'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file keyVault.bicep
            --parameters parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'set up server-level auditing to write audit logs to a storage account'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file sqlAuditing.bicep
            --parameters parameters.bicepparam

    - task: AzureCLI@2
      displayName: 'Configure Azure Active Directory'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Add commands to configure AAD

   

   
